name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Copy images directory (if exists)
        run: cp -R imgs build/imgs

      - name: Marp Build (README)
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: README.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Marp Build (index.pdf)
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: index.md --allow-local-files -o build/index.pdf
        env:
          MARP_USER: root:root

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
