name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Ensure build dir exists
        run: mkdir build

      - name: Copy images directory (if exists)
        run: cp -R imgs build/imgs

      - name: Marp Build (README)
        run: marp index.md --html -o build/index.html

      - name: Marp Build (index.pdf)
        run: marp index.md --html --allow-local-files -o build/index.pdf

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
